### ISSUE TITLE
ModuleNotFoundError: No module named '_sysconfigdata__android_aarch64_21_android'

### ISSUE THREAD

**Issue by batkins2** [pmp-p/pydk#16]
``File "/home/osboxes/Desktop/Code/pydk/aosp/apkroot-arm64-v8a/usr/lib/python3.8/sysconfig.py", line 422, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata__android_aarch64_21_android'
ERROR: pip install /home/osboxes/Desktop/Code/pydk/projects/requirements.txt failed
``
Any ideas?

**Comment by pmp-p** [comment]
thx for the report the triplet is set wrong it should be ```_sysconfigdata__linux_aarch64_21_android.py``` from ~~libpython~~ pip shell env, also the ANDROID_ABI is also wrong in the "shell.arm64-v8a.sh" 

should be fixed by https://github.com/pmp-p/pydk/commit/35f6ee3c9d43c348960193fb0b0259897e547dae

expected test result:
```
user@pp /data/cross/pydk $ . shell.arm64-v8a.sh 
[PyDK:arm64-v8a] /data/cross/pydk $ pip3-arm64-v8a install pip
Requirement already satisfied: pip in ./host/lib/python3.8/site-packages (20.2.4)
[PyDK:arm64-v8a] /data/cross/pydk $ 
```
