### ISSUE TITLE
cross-module.sh cross_pip

### ISSUE THREAD

**Issue by batkins2** [pmp-p/pydk#17]
https://github.com/pmp-p/pydk/blob/35f6ee3c9d43c348960193fb0b0259897e547dae/cross-modules.sh#L78

Should be:

``if cross_pip install -r $req``

**Comment by pmp-p** [comment]
good catch thanks , fixed in https://github.com/pmp-p/pydk/commit/a182699746297fc5b5d6455ac73422555dbcc29f
