### ISSUE TITLE
cross_pip.aosp.sh: line 3: all: command not found

### ISSUE THREAD

**Issue by batkins2** [pmp-p/pydk#18]
``+  cross_pip from : 
/home/osboxes/Desktop/Code/pydk/sources.aosp/cross_pip.aosp.sh: line 3: all: command not found``

**Comment by pmp-p** [comment]
thx should be fixed in https://github.com/pmp-p/pydk/commit/c29156931d22b02af6fd5fb8314990caa6134d05
