### ISSUE TITLE
No releases?

### ISSUE THREAD

**Issue by rowend36** [pmp-p/pydk#2]
Looks very nice.
I would like to test it on my kitkat device but I cannot find any releases.

//(Sorry if it's not really an issue)

**Comment by pmp-p** [comment]
no problem but actually android patchset relies on an unpublished python 3.7 alpha code base, so no point in making a release. I'm waiting for 3.7 rc1.

**Comment by pmp-p** [comment]
Meanwhile you may try the h3droid testcase https://github.com/pmp-p/h3droid/blob/sdk/usr/src/projects/uroot.term-debug.apk, cpython is ok but starting panda3d may not be obvious

**Comment by rowend36** [comment]
You're right. So I'll guess we'll  all wait the release, then. 
Thanks for the link. I'll try it out. Keep up the nice work.
