### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by amirouche** [pmp-p/pydk#5]
I would like to build cpython 3.x for the browser. I don't know how to proceed.

**Comment by pmp-p** [comment]
first step is to build an emscripten toolchain
https://github.com/pmp-p/pydk/tree/master/sources.em
or more detailed https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html

next use `./emsdkbuild.sh /work/path /path/to/emsdk_set_env.sh`
and enter env with ` .   /work/path/sdk.em.env`

for cpython the default recipe is `./Python3.7.1.build asm`
i'll add 3.7.2 very soon
